name: Create a release pull request

on:
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: (Test) Make changes to the repository
        run: npm install typescript webpack
      
      - name: (Test) Check npm version
        run: npm -v
      
      # document: https://github.com/marketplace/actions/create-pull-request
      - name: Create a release pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: pull request create test
          labels: Auto PR
          branch: release
          token: ${{ secrets.GITHUB }}
          delete-branch: true
