name: Create a release pull request

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    steps:
        # セマンティックバージョンのフォーマット検証（簡易版）
        # 厳密なものは下記のサイトの正規表現で行うこと
        # https://semver.org/
      - name: Verify semver
        run:  echo "${{ github.event.inputs.version }}" | grep -e ^\[0-9\]\\+.\[0-9\]\\+.\[0-9\]\\+$

      - uses: actions/checkout@master

        # ダミーの処理
      - name: (Test) Make changes to the repository
        run: npm install typescript webpack
      
        # ダミーの処理
      - name: (Test) Check npm version
        run: npm -v
      
        # ダミーの処理（ci/cdフロー内で変更がないとprが作成されないので、変更を無理やり作る）
      - name: (Test) Add code
        run: echo 'console.log(str)' >> index.js
      
      # document: https://github.com/marketplace/actions/create-pull-request
      - name: Create a release pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: pull request create test
          labels: Release PR
          branch: release-${{ github.event.inputs.version }}
          token: ${{ secrets.GITHUB }}
          delete-branch: true
        # 変更がないとブランチは作成されないので注意
        # workflow dispatchで値を受け入れることができるので、そこでバージョン指定しても良さそう
