name: Release

on:
  # NOTE: PRがマージされたときにワークフローを実行
  #       https://qiita.com/okazy/items/7ab46f2c20ec341a2836
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ github.event.pull_request.title }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check release version
        run: echo ${{ env.RELEASE_VERSION }}

      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
        with:
          tag_name: v${{ github.event.pull_request.title }}
          # release_name: ${{ github.event.pull_request.title }}
          # body: ${{ github.event.pull_request.body }}
          release_name: リリース名
          body: ボディ
          draft: false
          prerelease: false

  # NOTE: ビルドは並列処理
  # NOTE: すべてのビルドが成功したらリリースタグの設定とコンテナイメージをリポジトリにpushする

  # TODO: コンテナイメージのビルド(api)
  # TODO: docker hubにpush
  # TODO: github registryにpush

  # TODO: コンテナイメージのビルド(web)
  # TODO: docker hubにpush
  # TODO: github registryにpush

  # TODO: コンテナイメージのビルド(配布用)
  # TODO: docker hubにpush
  # TODO: github registryにpush
